version: "3.4"
services:
  app:
    build:
      context: .
    command: iex -S mix
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=NTUxNTAyODUwMTYxNzcwNTI2.D1x-ZQ.Xhozg5Hv3VlUbDS1tWHy7wJJRVU